# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 石小一
subtitle: 视己慎独
description: 做自己喜欢的事一件很痛苦的事情
author: Aierui
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.shijinrong.cn
root: /
permalink: :art/:id/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: p

# archive_generator:
#   per_page: 20
#   yearly: true
#   monthly: true

# tag_generator:
#   per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: https://github.com/Aierui/aierui.github.io
  branch: master

# 搜索服务
# algolia:
#   applicationID: 'BX8AIJO8N5'
#   apiKey: '4877f1cb6b8b471456faca6921e3268e'
#   adminApiKey: 'c7d88aa67fb806a758a75c8476ba6665'
#   indexName: 'blog.shijinrong.cn'
#   chunkSize: 5000

search:
  path: search.xml
  field: post
  format: html
  limit: 10000


